services:
  db:
    image: postgres:16

    container_name: demand_forecasting_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: demand_forecasting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: .

    container_name: demand_forecasting_backend

    restart: unless-stopped

    depends_on:
      - db

    env_file:
      - .env

    ports:
      - "8000:8000"


volumes:
  postgres_data: